# Generated by Django 3.2.20 on 2023-08-02 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('furniture_type', models.CharField(choices=[('couch', 'Couch'), ('armchair', 'Armchair'), ('dining table', 'Dining Table'), ('dining chair', 'Dining Chair'), ('desk', 'Desk'), ('bed', 'Bed'), ('dresser', 'Dresser'), ('locker', 'Locker'), ('coffee table', 'Coffee Table'), ('other', 'Other')], default='armchair', max_length=50)),
                ('room', models.CharField(choices=[('kitchen', 'Kitchen'), ('dining room', 'Dining Room'), ('bedroom', 'Bedroom'), ('study', 'Study'), ('living room', 'Living Room'), ('bathroom', 'Bathroom'), ('baby', 'Baby'), ('other', 'Other')], default='bathroom', max_length=50)),
                ('description', djrichtextfield.models.RichTextField(max_length=10000)),
                ('county', models.CharField(choices=[('antrim', 'Antrim'), ('armagh', 'Armagh'), ('carlow', 'Carlow'), ('cavan', 'Cavan'), ('clare', 'Clare'), ('cork', 'Cork'), ('derry', 'Derry'), ('donegal', 'Donegal'), ('down', 'Down'), ('dublin', 'Dublin'), ('fermanagh', 'Fermanagh'), ('galway', 'Galway'), ('kerry', 'Kerry'), ('kildare', 'Kildare'), ('kilkenny', 'Kilkenny'), ('laois', 'Laois'), ('leitrim', 'Leitrim'), ('limerick', 'Limerick'), ('longford', 'Longford'), ('louth', 'Louth'), ('mayo', 'Mayo'), ('meath', 'Meath'), ('monaghan', 'Monaghan'), ('offaly', 'Offaly'), ('roscommon', 'Roscommon'), ('sligo', 'Sligo'), ('tipperary', 'Tipperary'), ('tyrone', 'Tyrone'), ('waterford', 'Waterford'), ('westmeath', 'Westmeath'), ('wexford', 'Wexford'), ('wicklow', 'Wicklow')], default='antrim', max_length=50)),
                ('town', models.CharField(max_length=100)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[None, 400], upload_to='furniture/')),
                ('image_alt', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('as new', 'As New'), ('damaged', 'Damaged'), ('good condition, some damage', 'Good Condition, Some Damage')], default='as new', max_length=50)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('furniture_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='furniture.furniture')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
