# Generated by Django 3.2.20 on 2023-08-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_alter_comment_furniture_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='slug',
        ),
    ]
